apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: clustersecret
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "cluster-es"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels:
      name: app2

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      name: my-secret-store
      kind: SecretStore

    refreshInterval: "1h"
    target:
       name: my-kubernetes-secret # Secret name in k8s
    data:
    - secretKey: password # which key it's going to be stored
      remoteRef:
        key: super-secret # Our secret-name goes here
